### PR TITLE
Rename keybinds to be uniquie across mods

### PR DESCRIPTION
**Pull request by Pilzinsel64**
The story:
1. Nearly a year ago I made a PR: #26 
2. Sadly, I forgot to also change the keys in the lang files.
3. This PR has been made to fix this #30 But sadly, this returned to the previous (wrong) behavior.
4. Now I made this PR to fix this again - completely this time.

The reason:
Each single time we start minecraft, the keybinds for this mod get lost, because they conflict with another mod (AE2FC, iirc).

I hope this is fine now. :)

### CODE REVIEW

**Comment by Pilzinsel64** [comment]
Err, is the build failing because my change? I hope that's just because a server is down. 😳

**Comment by bombcar** [comment]
* What went wrong:
Could not determine the dependencies of task ':extractForgeUserdev'.
> Could not resolve all files for configuration ':forgeUserdev'.
   > Could not resolve net.minecraftforge:forge:1.7.10-10.13.4.1614-1.7.10.
     Required by:
         project :
      > Could not resolve net.minecraftforge:forge:1.7.10-10.13.4.1614-1.7.10.
         > Could not get resource 'https://maven.ic2.player.to/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10.pom'.
            > Could not GET 'https://maven.ic2.player.to/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10.pom'.
               > Connect to maven.ic2.player.to:443 [maven.ic2.player.to/141.28.27.36] failed: Connect timed out

Let's try poking it

**Comment by bombcar** [comment]
maven.ic2.player.to is down.

**Comment by mitchej123** [comment]
Update the buildscript, should work around that.

**Comment by Pilzinsel64** [comment]
Alright! But can't today, going to bed now. Will setup a local workspace and update build script tomorrow then. :/

**Comment by Dream-Master** [comment]
@Pilzinsel64 https://github.com/Pilzinsel64/WirelessCraftingTerminal/pull/1

**Comment by Dream-Master** [comment]
@Pilzinsel64 https://github.com/Pilzinsel64/WirelessCraftingTerminal/pull/2

**Comment by Dream-Master** [comment]
@Pilzinsel64 last one https://github.com/Pilzinsel64/WirelessCraftingTerminal/pull/3

**Review by Dream-Master — APPROVED** [review]

**Comment by Dream-Master** [comment]
added with https://github.com/GTNewHorizons/WirelessCraftingTerminal/commit/075d77b14ec299a1518c7a7dcac64be85ccadc4e

**Pull request closed without merging**
